const geoLocationSchema = {
    results: [
      {
        id: null,
        name: null,
        latitude: null,
        longitude: null,
        elevation: null,
        feature_code: null,
        country_code: null,
        admin1_id: null,
        admin2_id: null,
        timezone: null,
        population: null,
        postcodes: [
          null,
          null
        ],
        country_id: null,
        country: null,
        admin1: null,
        admin2: null
      },
      {
        id: null,
        name: null,
        latitude: null,
        longitude: null,
        elevation: null,
        feature_code: null,
        country_code: null,
        admin1_id: null,
        admin2_id: null,
        admin3_id: null,
        timezone: null,
        population: null,
        postcodes: [
          null
        ],
        country_id: null,
        country: null,
        admin1: null,
        admin2: null,
        admin3: null
      },
      {
        id: null,
        name: null,
        latitude: null,
        longitude: null,
        elevation: null,
        feature_code: null,
        country_code: null,
        admin1_id: null,
        admin2_id: null,
        admin3_id: null,
        timezone: null,
        population: null,
        postcodes: [
          null
        ],
        country_id: null,
        country: null,
        admin1: null,
        admin2: null,
        admin3: null
      },
      {
        id: null,
        name: null,
        latitude: null,
        longitude: null,
        elevation: null,
        feature_code: null,
        country_code: null,
        admin1_id: null,
        admin2_id: null,
        timezone: null,
        postcodes: [
          null
        ],
        country_id: null,
        country: null,
        admin1: null,
        admin2: null
      },
      {
        id: null,
        name: null,
        latitude: null,
        longitude: null,
        elevation: null,
        feature_code: null,
        country_code: null,
        admin1_id: null,
        admin2_id: null,
        timezone: null,
        postcodes: [
          null
        ],
        country_id: null,
        country: null,
        admin1: null,
        admin2: null
      },
      {
        id: null,
        name: null,
        latitude: null,
        longitude: null,
        elevation: null,
        feature_code: null,
        country_code: null,
        admin1_id: null,
        admin2_id: null,
        timezone: null,
        postcodes: [
          null,
          null
        ],
        country_id: null,
        country: null,
        admin1: null,
        admin2: null
      },
      {
        id: null,
        name: null,
        latitude: null,
        longitude: null,
        elevation: null,
        feature_code: null,
        country_code: null,
        admin1_id: null,
        admin2_id: null,
        timezone: null,
        population: null,
        country_id: null,
        country: null,
        admin1: null,
        admin2: null
      },
      {
        id: null,
        name: null,
        latitude: null,
        longitude: null,
        elevation: null,
        feature_code: null,
        country_code: null,
        admin1_id: null,
        admin2_id: null,
        admin3_id: null,
        timezone: null,
        population: null,
        country_id: null,
        country: null,
        admin1: null,
        admin2: null,
        admin3: null
      },
      {
        id: null,
        name: null,
        latitude: null,
        longitude: null,
        elevation: null,
        feature_code: null,
        country_code: null,
        admin1_id: null,
        admin2_id: null,
        admin3_id: null,
        timezone: null,
        population: null,
        country_id: null,
        country: null,
        admin1: null,
        admin2: null,
        admin3: null
      },
      {
        id: null,
        name: null,
        latitude: null,
        longitude: null,
        elevation: null,
        feature_code: null,
        country_code: null,
        admin1_id: null,
        admin2_id: null,
        timezone: null,
        country_id: null,
        country: null,
        admin1: null,
        admin2: null
      }
    ],
    generationtime_ms: null
  }
 export default geoLocationSchema;  